import and preprocessing the given datasets

In [ ]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
data=pd.read_csv('/content/movies_dataset.csv')

In [ ]:
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
data.shape

(4803, 24)

In [ ]:
selectedFeatures = ['genres','keywords','overview','tagline','cast','director']
print(selectedFeatures)

['genres', 'keywords', 'overview', 'tagline', 'cast', 'director']


In [ ]:
for feature in selectedFeatures:
  data[feature]=data[feature].fillna("")

In [ ]:
comFeatures = data['genres']+data['keywords']+data['overview']+data['tagline']+data['cast']+data['director']
print(comFeatures)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    When ambitious New York attorney Sam is sent t...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [ ]:
vector = TfidfVectorizer()
featureVector = vector.fit_transform(comFeatures)
print(featureVector)

  (0, 621)	0.05911539726785288
  (0, 888)	0.06831187369794306
  (0, 13475)	0.08931043654309764
  (0, 32466)	0.07579564078555111
  (0, 13958)	0.20972605417816462
  (0, 6764)	0.14848593383905964
  (0, 15193)	0.10745216102382323
  (0, 34246)	0.23560169293495883
  (0, 39574)	0.08541092637886738
  (0, 7147)	0.16694643157272984
  (0, 34031)	0.20972605417816462
  (0, 36379)	0.0798163154982304
  (0, 259)	0.18784891476317275
  (0, 6102)	0.12106169143301407
  (0, 27359)	0.1931766370808179
  (0, 23334)	0.1388051454283183
  (0, 19553)	0.039729671802685156
  (0, 10451)	0.17662721998347122
  (0, 37142)	0.029567815672023285
  (0, 24875)	0.14671654953539742
  (0, 27281)	0.3596307674601816
  (0, 26701)	0.047141879587700324
  (0, 38554)	0.1475848547512471
  (0, 24599)	0.10540215728635756
  (0, 5303)	0.05902857621954242
  :	:
  (4802, 28968)	0.0896934878273717
  (4802, 12557)	0.08192558473731587
  (4802, 32636)	0.081721766148852
  (4802, 8154)	0.1094072234217114
  (4802, 19935)	0.09889905110323315
  (480

In [ ]:
similarity = cosine_similarity(featureVector)
print(similarity)
similarity.shape

[[1.         0.04651794 0.02122374 ... 0.02538798 0.03210693 0.00612798]
 [0.04651794 1.         0.03945313 ... 0.04955816 0.03187544 0.01488931]
 [0.02122374 0.03945313 1.         ... 0.02570582 0.01200746 0.01342171]
 ...
 [0.02538798 0.04955816 0.02570582 ... 1.         0.03869624 0.02633318]
 [0.03210693 0.03187544 0.01200746 ... 0.03869624 1.         0.03292613]
 [0.00612798 0.01488931 0.01342171 ... 0.02633318 0.03292613 1.        ]]


(4803, 4803)

Now we are moving into recommendation algorithm

In [ ]:
movieName = input('Enter your favourite movie name: ')

Enter your favourite movie name: Avengers


In [ ]:
listTitles = data['title'].tolist()
print(listTitles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
findCloseMatch = difflib.get_close_matches(movieName,listTitles)
print(findCloseMatch)

['The Avengers', 'Swingers']


In [ ]:
closeMatch=findCloseMatch[0]
print(closeMatch)

The Avengers


In [ ]:
movieIndex = data[data.title == closeMatch]['index'].values[0]
print(movieIndex)

16


In [ ]:
similarityScore = list(enumerate(similarity[movieIndex]))
print(similarityScore)

[(0, 0.029895375008071462), (1, 0.04884838546310437), (2, 0.034392717595695226), (3, 0.0345340611005966), (4, 0.0610391405697736), (5, 0.018301618058203264), (6, 0.02463672071595775), (7, 0.3815489758059939), (8, 0.034685373360138994), (9, 0.07413775557918943), (10, 0.04800145838485781), (11, 0.020607413796250116), (12, 0.013331566520340307), (13, 0.025544818705026617), (14, 0.10183988293124893), (15, 0.02971715014248751), (16, 0.9999999999999999), (17, 0.052144149960778235), (18, 0.0866879521780724), (19, 0.0421617482718588), (20, 0.07124628370113481), (21, 0.04645249604347047), (22, 0.0235687340700795), (23, 0.01656030638731385), (24, 0.02678381874165494), (25, 0.027841422621786543), (26, 0.14326343394228308), (27, 0.05995020483630337), (28, 0.05573675422513397), (29, 0.05726774387291532), (30, 0.08227452822185422), (31, 0.09435378790025728), (32, 0.04003597603174631), (33, 0.11411725834054842), (34, 0.010280443495255955), (35, 0.033968060887817696), (36, 0.0525825205764399), (37, 0.

In [ ]:
SortedSimilarMovies=sorted(similarityScore, key = lambda x:x[1],reverse=True)
print(SortedSimilarMovies)

[(16, 0.9999999999999999), (7, 0.3815489758059939), (79, 0.18054385650274704), (85, 0.17773389532585354), (174, 0.17413870034917528), (511, 0.14888753494091722), (64, 0.14402040089997895), (26, 0.14326343394228308), (126, 0.1277813304840715), (203, 0.11688181655906192), (46, 0.11564949440327245), (129, 0.11542155935794005), (33, 0.11411725834054842), (4401, 0.11295773047790766), (182, 0.11085068311145803), (68, 0.10982268715375194), (101, 0.10638185234150077), (14, 0.10183988293124893), (1892, 0.10045866465765256), (788, 0.10016411565800545), (1286, 0.09951496958533686), (38, 0.09843999784095805), (870, 0.09753559003337794), (215, 0.09491327566515105), (31, 0.09435378790025728), (2235, 0.0917744225625701), (1720, 0.09140325276708391), (169, 0.09117472311960974), (421, 0.09103244464000848), (94, 0.091028304870537), (3311, 0.08924910322379989), (91, 0.08700740479994772), (18, 0.0866879521780724), (2874, 0.08634787219448786), (1569, 0.08542284708475387), (3751, 0.08517313068898731), (1275

In [ ]:
print("Movie suggest for you : \n")
i=1
for movie in SortedSimilarMovies:
  index = movie[0]
  titlefromIndex = data[data.index==index]["title"].values[0]
  if(i<=30):
    print(i,".",titlefromIndex)
    i+=1

Movie suggest for you : 

1 . The Avengers
2 . Avengers: Age of Ultron
3 . Iron Man 2
4 . Captain America: The Winter Soldier
5 . The Incredible Hulk
6 . X-Men
7 . X-Men: Apocalypse
8 . Captain America: Civil War
9 . Thor: The Dark World
10 . X2
11 . X-Men: Days of Future Past
12 . Thor
13 . X-Men: The Last Stand
14 . The Helix... Loaded
15 . Ant-Man
16 . Iron Man
17 . X-Men: First Class
18 . Man of Steel
19 . The Losers
20 . Deadpool
21 . Snowpiercer
22 . The Amazing Spider-Man 2
23 . Superman II
24 . Fantastic 4: Rise of the Silver Surfer
25 . Iron Man 3
26 . A Scanner Darkly
27 . Kick-Ass
28 . Captain America: The First Avenger
29 . Zodiac
30 . Guardians of the Galaxy


Movie Recommendation System

In [ ]:
try:
  movieName = input('Enter your favourite movie name: ')

  listTitles = data['title'].tolist()

  findCloseMatch = difflib.get_close_matches(movieName,listTitles)

  closeMatch=findCloseMatch[0]

  movieIndex = data[data.title == closeMatch]['index'].values[0]

  similarityScore = list(enumerate(similarity[movieIndex]))

  SortedSimilarMovies=sorted(similarityScore, key = lambda x:x[1],reverse=True)

  print("Movie suggest for you : \n")
  i=1
  for movie in SortedSimilarMovies:
    index = movie[0]
    titlefromIndex = data[data.index==index]["title"].values[0]
    if(i<=30):
      print(i,".",titlefromIndex)
      i+=1
except:
  print("oops the movie you are searching is not found in the dataset.we will soon update the dataset")

Enter your favourite movie name: Avengers
Movie suggest for you : 

1 . The Avengers
2 . Avengers: Age of Ultron
3 . Iron Man 2
4 . Captain America: The Winter Soldier
5 . The Incredible Hulk
6 . X-Men
7 . X-Men: Apocalypse
8 . Captain America: Civil War
9 . Thor: The Dark World
10 . X2
11 . X-Men: Days of Future Past
12 . Thor
13 . X-Men: The Last Stand
14 . The Helix... Loaded
15 . Ant-Man
16 . Iron Man
17 . X-Men: First Class
18 . Man of Steel
19 . The Losers
20 . Deadpool
21 . Snowpiercer
22 . The Amazing Spider-Man 2
23 . Superman II
24 . Fantastic 4: Rise of the Silver Surfer
25 . Iron Man 3
26 . A Scanner Darkly
27 . Kick-Ass
28 . Captain America: The First Avenger
29 . Zodiac
30 . Guardians of the Galaxy
